{% set name = "pycoingecko" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycoingecko-{{ version }}.tar.gz
  sha256: bd49d92f918bc3f03ba9c042558844992576fbee859e438ddeafefd41861d2b1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests

test:
  imports:
    - pycoingecko
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/man-c/pycoingecko
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: Python wrapper for the CoinGecko API
  description: |
    Python3 wrapper around the CoinGecko API (V3)
  doc_url: https://github.com/man-c/pycoingecko
  dev_url: https://github.com/man-c/pycoingecko

extra:
  recipe-maintainers:
    - jan-janssen
